function [H_loss_total_discharging, H_loss_minor_discharging, H_loss_major_discharging, H_loss_major_umbilical_discharging, H_loss_minor_umbilical_discharging,...
            H_static_discharging, H_turbine, Q_turbine, V_wat_rigid_discharging, V_wat_bladder, P_generator, N_roundtrip, T_empty_discharging, E_elec_out_kWh, i]=Discharging(OB_GUI_parameters,V_wat_rigid_charging,E_elec_in_J)
%% DISCHARGING MODEL
%   This model simulates the discharging phase of the Ocean Battery.

%% Charging the Ocean Battery 
% Charging; %Runs the charging script. 

%% Setting parameters
OB_parameters; %Sets the parameters specified in OB parameters.

%% Initial calculations
A_turbine = pi * (0.5*D_turbine)^2; %[m^2] Area of the turbine outlet.
Interp_steps = (1/Delta_t)+1; %Calculates the required amount of steps between two seconds based on Delta_t. Is used in interpolation. 
startup_steps = (1/Delta_t)*t_open_ball_valve; %[-] Number of iterations that passes while the ball valve opens up.

%% Model initialization
i = 1; %Initial value for i.
V_wat_bladder(1) = V_wat_rigid_charging(1)-V_wat_rigid_charging(end) + (Capacity_rigid - V_wat_rigid_charging(1)); %[m^3] Initial value for the volume of water present in the bladder.
Q_turbine_a(1) = 2.6e-3; %[m^3/s] Initial guess of the flow throught the turbine. 

%% Overshoot correction
%   The volume that is left in the reservoir is almost always a negative
%   number because charging script slightly "overshoots" the emptying of 
%   the rigid reservoir. This if-statement ensures that the starting volume
%   of the rigid reservoir is either zero (empty) or larger than zero. 
if V_wat_rigid_charging(end) < 0
    V_wat_rigid_discharging(1) = 0;
else
    V_wat_rigid_discharging(1) = V_wat_rigid_charging(end);
end

%% Reality check
if V_wat_bladder(1) < V_wat_bladder_end
    error('ERROR: End volume of the bladder exceeds the starting volume of the bladder during the discharge phase. Impossible situation.');
end

%% Calculation of the starting flow
%   The behaviour of the system during the first "t_open_ball_valve" 
%   seconds of operation is calculated. "t_open_ball_valve" seconds is the 
%   time required to open the ball valve. When the ball valve is fully 
%   opened, the "startup-phase" is completed. The flow (Q_turbine) after 12
%   seconds will be used to model this phase. The startup is assumed to be
%   instant in this part. 

for i = 1:startup_steps
    [~, ~, ~, ~, ~, ~, ~, ~, V_wat_rigid_discharging(i+1), ~, Q_turbine_a(i+1)] = ...
        Discharging_step(Q_turbine_a(i), V_wat_rigid_discharging(i), V_wat_bladder(1), ...
        OB_GUI_parameters, A_turbine, Interp_steps);
end

%% Flow during the startup phase
%   A liniar line is plotted between 0 and the flow (Q_turbine) after 
%   "t_open_ball_valve" seconds. This represents the increasing flow due to
%   the opening of the ball valve. This "startup phase" is assumed to be 
%   linear. 
Q_turbine = linspace(0,Q_turbine_a(startup_steps),startup_steps); %[m^3/s] Linear line between 0 and Q_turbine after "t_open_ball_valve" seconds. 

%% Other parameters during startup phase
%   The other parameters during the startup phase are determined in this
%   for loop, based on the flow throught the turbine during the first 
%   "t_open_ball_valve" seconds of operation.  

for i = 1:startup_steps
    [H_loss_total_discharging(i), H_loss_minor_discharging(i), H_loss_major_discharging(i), ...
        H_loss_major_umbilical_discharging(i), H_loss_minor_umbilical_discharging(i), ...
        H_static_discharging(i), H_turbine(i), P_generator(i), ...
        V_wat_rigid_discharging(i+1), V_wat_bladder(i+1), ~] = Discharging_step( ...
        Q_turbine(i), V_wat_rigid_discharging(i), V_wat_bladder(i), ...
        OB_GUI_parameters, A_turbine, Interp_steps);
end

%% While loop
%   The behaviour of the system after the "startup phase" is described by
%   this while loop. 
while  V_wat_bladder(i) > V_wat_bladder_end 
    [H_loss_total_discharging(i), H_loss_minor_discharging(i), H_loss_major_discharging(i), ...
        H_loss_major_umbilical_discharging(i), H_loss_minor_umbilical_discharging(i), ...
        H_static_discharging(i), H_turbine(i), P_generator(i), ...
        V_wat_rigid_discharging(i+1), V_wat_bladder(i+1), Q_turbine(i+1)] = Discharging_step( ...
        Q_turbine(i), V_wat_rigid_discharging(i), V_wat_bladder(i), ...
        OB_GUI_parameters, A_turbine, Interp_steps);

% Move to the next iteration.     
i = i+1;
end

%% Output variables
T_empty_discharging = i*Delta_t; %[s] Time it takes to discharge the battery.
E_elec_out_J = sum(P_generator.*Delta_t); %[J] Amount of energy generated by the generator during the discharging.
E_elec_out_Wh = E_elec_out_J/3600; %[Wh] Amount of energy generated by the generator during the discharging.
E_elec_out_kWh = E_elec_out_Wh/1000; %[kWh] Amount of energy generated by the generator during the discharging.

%% Plots 
x_for_plot = 1:i-1;
x_for_plot_2 = 1:i;
x_for_plot_3 = 1:startup_steps+1;

figure(5)
plot(Q_turbine)
title('Flow through the turbine (Discharging)')
if Delta_t == 0.1
    xlabel('Time [ds]');
elseif Delta_t == 0.01
    xlabel('Time [cs]');
elseif Delta_t == 0.001
    xlabel('Time [ms]');
end
ylabel('Volumetric flowrate [m^3/s]')


figure(6)
plot(x_for_plot_2, V_wat_rigid_discharging, x_for_plot_2, V_wat_bladder)
title('Water in bladder and rigid reservoir (Discharging)')
if Delta_t == 0.1
    xlabel('Time [ds]');
elseif Delta_t == 0.01
    xlabel('Time [cs]');
elseif Delta_t == 0.001
    xlabel('Time [ms]');
end
ylabel('Volume [m^3]')
legend('Rigid reservoir','Bladder')

figure(7)
plot(x_for_plot, H_loss_total_discharging, x_for_plot, H_loss_minor_discharging, x_for_plot, H_loss_major_discharging, x_for_plot, H_loss_major_umbilical_discharging, x_for_plot, H_loss_minor_umbilical_discharging)
title('Head loss (Discharging)')
if Delta_t == 0.1
    xlabel('Time [ds]');
elseif Delta_t == 0.01
    xlabel('Time [cs]');
elseif Delta_t == 0.001
    xlabel('Time [ms]');
end
ylabel('Head loss [m]')
legend('Total head loss','Minor head loss','Major head loss','Major head loss umbilical','Minor head loss umbilical')

figure(8)
plot(x_for_plot, H_static_discharging, x_for_plot, H_loss_total_discharging, x_for_plot, H_turbine)
title('Turbine head (Discharging)')
if Delta_t == 0.1
    xlabel('Time [ds]');
elseif Delta_t == 0.01
    xlabel('Time [cs]');
elseif Delta_t == 0.001
    xlabel('Time [ms]');
end
ylabel('Head [m]')
legend('Static head','Total head loss','Turbine head')

figure(9)
plot(P_generator)
title('Power of the generator (Discharging)')
if Delta_t == 0.1
    xlabel('Time [ds]');
elseif Delta_t == 0.01
    xlabel('Time [cs]');
elseif Delta_t == 0.001
    xlabel('Time [ms]');
end
ylabel('Power of the generator [W]')

%% Roundtrip efficiency calculation
Analytical_Discharging;
N_roundtrip = n_Total;

end
